### Visualizing Government Debt
##### Total Debt, as a percentage of GDP.
This visualization is a simple bar chart to illustrate and compare the magnitude of debt for each country, expressed as a percentage of that Country's GDP. For values greater than 100%, the country's debt exceeds its GDP. The bar chart shows that there are 10 countries with ratios greater than 100%. These are located on the right hand side of the chart, from Canada to Japan. For the remaining 24 countries, GDP exceed debt. Comparing the largest ratio (Japan: 234) to the smallest ratio (Estonia:13), shows us that Japan's ratio is 18 times larger than Estonia's. 18, then, is the largest relative difference in this visualization. By clicking on a bar or country of interest, the user can change the color of that bar in order to help distinguish it from others and thereby have an easier time making comparisons.

<iframe src="https://data.oecd.org/chart/65Fh" width="860" height="645" style="border: 0" mozallowfullscreen="true" webkitallowfullscreen="true" allowfullscreen="true"><a href="https://data.oecd.org/chart/65Fh" target="_blank">OECD Chart: General government debt, Total, % of GDP, Annual, 2017</a></iframe>

##### Sparklines: Debt-to-GDP Ratios Over Time
In this visualization, I've created a grid of line charts to show a snapshot or "sparkline" of how the debt-to-GDP ratio has changed for each country from 1995 to the present day. Each line chart has a dot representing the most recent data point on record for that country. The data used in this visualization comes from the Organization for Economic Cooperation and Development (OECD). It is important to point out that not all countries have data for each year over the 24 year time period. For example, Luxembourg, Chile, Turkey, Israel, Columbia and Mexico all have missing values over that time period. By looking at the general shape of the the sparkline, the viewer can get a general idea of have the Debt-to-GDP ratio has changed over time. If the line is increasing from left to right, the ratio is increasing over that time. If the line is decreasing over that time, the ratio is also decreasing, and if the line is relatively flat, the ratio hasn't changed much. The viewer can also look to see if the lines look relatively stable or straight, of if they seem to have sudden jumps of "kinks," as is the case with countries like Ireland and Latvia. These sudden jumps might be indicative or larger economic factors that had sudden and signficant impact on either GDP, debt, or both. For example, on the sparkline for the United States, we can see the line is relatively flat up until 2007, followed by steady increase from 2007 to 2011, and then slight increases after that point. These trends seem to correspond to the U.S. recovery to the 2007-2008 recession.

<div class="flourish-embed flourish-chart" data-src="visualisation/3749016" data-url="https://flo.uri.sh/visualisation/3749016/embed" aria-label="" data-width="90%"><script src="https://public.flourish.studio/resources/embed.js"></script></div>

##### Boxplots: Distributions of Debt-to-GDP Ratios for 
Boxplots can be useful visualizations for understanding the distribution of values for a certain feature or attribute of interest. In this case, the attribute of interest is the Debt-to-GDP ratio. Boxplots make interpreting the distribution easy: to understand the spread of data, look from one tail to the other tail. The greater the distance between the ends of the tails, the greater the spread of data. In some cases, outliers are shown in the area beyond the tails. The box portion of the boxplot shows the interquartile range: the distance between the 25th and 7th percentile and all the values contained within that range. Finally, the line located somewhere between the 25th and 75th percentiles, though not necessarily directly in the middle, represents the median.

I have many critiques of this visualization that I would choose to improve if the Flourish editing environment allowed me to. First, I ultimately made the decision to not include an "All" option on the filter selector. The "All" option would have plotted all of the boxplots for each country side by side in one chart. While displaying multiple boxplots side by side offers the benefit of being able to compare distributions (both the center and the spread), I decided that there were simply too many boxplots and the crowded and chaotic nature of too many plots outweighs the benefit gained by being able to compare these plots. Unfortunately, the filtering feature provided by Flourish does not seem to have the functionality to select multiple categories (for example, 3 or 5) to compare. To my knowledge, it only allows for one or all to be selected. If there were enhanced functionality, I would like to be able to select a small number of countries using this filter and then order them along the x-axis based on a particular attribute. For example, I might order the resulting boxplots in a descending fashion from left to right based on the maximum Debt-to-GDP ratio for each country, or perhaps in a descending order based on the size of the range in the data. Additionally, I would add that there are a few things that could be done to the data itself to strengthen this visualization. First, countries could be grouped or assigned to groups based on similarities like population size, continent, or other economic factors. Then, boxplots could be made for each grouping. Additionally, boxplots work best when there is a large number of observations. Most of the countries in this dataset have about 25 observations and some have less than this. A larger number would be ideal.

<div class="flourish-embed flourish-scatter" data-src="visualisation/3749367" data-url="https://flo.uri.sh/visualisation/3749367/embed" aria-label="" data-width="60%"><script src="https://public.flourish.studio/resources/embed.js"></script></div>
